#!/bin/sh

declare -a arr=($(find `pwd` -type d -maxdepth 1))

for i in "${arr[@]}"
do
    	cd $i

	# is this a git dir
	if [ -d .git ]; then

    		declare -a gitstatus=`git status -b`
    		if [[ $gitstatus != *nothing* ]]; then
			echo "changes detected in $i"
		fi
	fi
done

